"""tabelas iniciais

Revision ID: 83a04feaade0
Revises: 
Create Date: 2026-05-18 10:12:18.089775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a04feaade0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuidadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('eh_admin', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('idosos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('condicoes', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.String(length=300), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idoso_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('dosagem', sa.String(length=60), nullable=True),
    sa.Column('instrucoes', sa.Text(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idoso_id'], ['idosos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idoso_id', sa.Integer(), nullable=False),
    sa.Column('cuidador_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('periodo', sa.Enum('manha', 'tarde', 'noite', name='periodo_turno'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fim', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('agendado', 'em_andamento', 'concluido', 'cancelado', name='status_turno'), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cuidador_id'], ['cuidadores.id'], ),
    sa.ForeignKeyConstraint(['idoso_id'], ['idosos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idoso_id', 'data', 'periodo', name='uq_turno_idoso_dia_periodo')
    )
    op.create_table('administracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('cuidador_id', sa.Integer(), nullable=False),
    sa.Column('data_prevista', sa.DateTime(), nullable=False),
    sa.Column('data_real', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'administrado', 'pulado', name='status_adm'), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cuidador_id'], ['cuidadores.id'], ),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horarios_remedios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.SmallInteger(), nullable=True),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_cuidado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('idoso_id', sa.Integer(), nullable=False),
    sa.Column('cuidador_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('humor', sa.Enum('otimo', 'bom', 'neutro', 'agitado', 'triste', name='humor_idoso'), nullable=True),
    sa.Column('alimentacao', sa.Text(), nullable=True),
    sa.Column('hidratacao', sa.Text(), nullable=True),
    sa.Column('eliminacoes', sa.Text(), nullable=True),
    sa.Column('mobilidade', sa.Text(), nullable=True),
    sa.Column('intercorrencias', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cuidador_id'], ['cuidadores.id'], ),
    sa.ForeignKeyConstraint(['idoso_id'], ['idosos.id'], ),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_cuidado')
    op.drop_table('horarios_remedios')
    op.drop_table('administracoes')
    op.drop_table('turnos')
    op.drop_table('medicamentos')
    op.drop_table('idosos')
    op.drop_table('cuidadores')
    # ### end Alembic commands ###
